**a. Import libary:**

In [1]:
import pandas as pd
import numpy as np

**b. Import file:**

In [3]:
df = pd.read_csv('../data/raw/retail_sales_data.csv')
df.head()

,transaction_id,sale_date,sale_time,customer_id,gender,age,age_group,city,store_branch,membership_tier,...,cogs,discount_event,discount_pct,discount_amount,total_sale,profit,profit_margin_pct,payment_method,customer_rating,return_flag
0,TXN-01009,7/23/2023,16:45:00,CUST-0171,Female,32.0,26-35,Chittagong,GEC Circle,Gold,...,26.98,Flash Sale,15,7.30,41.34,14.36,34.74,Debit Card,2.8,No
1,TXN-00515,12/9/2024,13:34:00,CUST-0064,NaN,21.0,18-25,Narayanganj,Tanbazar,Silver,...,124.77,Flash Sale,10,19.91,179.17,54.40,30.36,Cash,1.9,No
2,TXN-00167,1/15/2024,11:02:00,CUST-0371,Female,28.0,26-35,Rajshahi,Shaheb Bazar,Platinum,...,20.76,NaN,0,0.00,102.1,60.58,59.33,Mobile Payment,NaN,No
3,TXN-01318,6/5/2024,15:26:00,CUST-0361,Male,39.0,36-45,Narayanganj,Deobhog,Bronze,...,33.17,NaN,0,0.00,224.67,125.16,55.71,Gift Card,4.5,No
4,TXN-00013,1/17/2023,13:04:00,CUST-0052,Female,45.0,36-45,Mymensingh,Charpara,Silver,...,510.93,NaN,0,0.00,1833.58,811.72,44.27,Credit Card,3.2,No

**c. Checking data type:**

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2045 entries, 0 to 2044
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     2045 non-null   str
 1   sale_date          2045 non-null   str
 2   sale_time          2045 non-null   str
 3   customer_id        2045 non-null   str
 4   gender             2005 non-null   str
 5   age                2011 non-null   float64
 6   age_group          2045 non-null   str
 7   city               2010 non-null   str
 8   store_branch       2037 non-null   str
 9   membership_tier    1999 non-null   str
 10  sales_channel      2045 non-null   str
 11  category           2045 non-null   str
 12  product_name       2018 non-null   str
 13  quantity           2045 non-null   int64
 14  price_per_unit     2045 non-null   float64
 15  cogs               2045 non-null   float64
 16  discount_event     1142 non-null   str
 17  discount_pct       2045 non-null   int64
 18  discount_amount    2045 non-null   float64
 19  total_sale         2045 non-null   str
 20  profit             2045 non-null   float64
 21  profit_margin_pct  2045 non-null   float64
 22  payment_method     2015 non-null   str
 23  customer_rating    1995 non-null   float64
 24  return_flag        2045 non-null   str
dtypes: float64(7), int64(2), str(16)
memory usage: 399.5 KB

**checking hidden columns' type:**

In [47]:
df.iloc[:, 20:25].info()

<class 'pandas.DataFrame'>
RangeIndex: 2045 entries, 0 to 2044
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   profit             2045 non-null   float64
 1   profit_margin_pct  2045 non-null   float64
 2   payment_method     2015 non-null   str
 3   customer_rating    1995 non-null   float64
 4   return_flag        2045 non-null   str
dtypes: float64(3), str(2)
memory usage: 80.0 KB

**d. Data Normalization & Formatting:**

In [48]:
df['total_sale'] = df['total_sale'].replace(r'[^\d.]', '', regex=True)

df['total_sale'] = pd.to_numeric(df['total_sale'], errors='coerce')

print(df['total_sale'].dtype)

float64

**e. Data Sanitization :**

**i. Text Normalization :**

In [49]:
text_cleaning = df.select_dtypes(include='string').columns

df[text_cleaning] = df[text_cleaning].apply(lambda col: col.str.strip().str.title())

**ii. Invalid Value Replacement :**

In [50]:
df = df.replace(r'^\s*$', np.nan, regex=True).replace(['?', '??', 'N/A', '-', 'Unknown', 'Tbd'], np.nan)

**f. Categorical Value Cleaning :**

**i. Checking and Cleaning Data  of `sale_date` column :**

In [51]:
print(df['sale_date'].unique())

<StringArray>
[ '7/23/2023',  '12/9/2024',  '1/15/2024',   '6/5/2024',  '1/17/2023',
   '6/7/2024', '12/28/2023',  '2/17/2024',  '6/13/2023',  '2/19/2024',
 ...
   '9/1/2024',  '12/5/2024',  '7/22/2024',  '7/17/2023',  '10/5/2023',
  '8/21/2023', '10/13/2024',  '9/10/2023',   '5/6/2024',   '2/8/2023']
Length: 685, dtype: str

In [52]:
df['sale_date'] = pd.to_datetime(df['sale_date'], dayfirst=False, errors='coerce')
df['sale_date'] = df['sale_date'].dt.strftime('%Y-%m-%d').where(df['sale_date'].notna(), None)

print(df['sale_date'].unique())

<StringArray>
['2023-07-23', '2024-12-09', '2024-01-15', '2024-06-05', '2023-01-17',
 '2024-06-07', '2023-12-28', '2024-02-17', '2023-06-13', '2024-02-19',
 ...
 '2024-09-01', '2024-12-05', '2024-07-22', '2023-07-17', '2023-10-05',
 '2023-08-21', '2024-10-13', '2023-09-10', '2024-05-06', '2023-02-08']
Length: 681, dtype: str

**ii. Checking and Cleaning Data  of `age` column :**

In [53]:
df['gender'].value_counts()

gender
Female    1065
Male       921
Mal          8
F            4
Femal        4
M            3
Name: count, dtype: int64

In [54]:
df['gender'] = df['gender'].replace({
        'Mal' : 'Male',
        'M' : 'Male',
        'F' : 'Female',
        'Femal' : 'Female'
})

df['gender'].value_counts()

gender
Female    1073
Male       932
Name: count, dtype: int64

**iii. Checking and Cleaning Data  of `category` column :**

In [55]:
df['category'].value_counts()

category
Books & Stationery    287
Food & Grocery        265
Beauty                256
Toys & Kids           252
Home & Garden         244
Clothing              227
Sports                226
Electronics           223
Sport                  11
Beauity                10
Beuty                  10
Sprots                  9
Electrnics              7
Clthing                 7
Electronis              6
Clothng                 5
Name: count, dtype: int64

In [56]:
df['category'] = df['category'].replace({
      'Sport' : 'Sports',
      'Sprots' : 'Sports',
      'Electrnics' : 'Electronics',
      'Electronis' : 'Electronics',
      'Beuty' : 'Beauty',
      'Beauity' : 'Beauty',
      'Clthing' : 'Clothing',
      'Clothng' : 'Clothing'

})
df['category'].value_counts()

category
Books & Stationery    287
Beauty                276
Food & Grocery        265
Toys & Kids           252
Sports                246
Home & Garden         244
Clothing              239
Electronics           236
Name: count, dtype: int64

**iv. Checking and Cleaning Data  of `payment_method` column :**

In [57]:
df['payment_method'].value_counts()

payment_method
Cash              418
Credit Card       414
Mobile Payment    406
Gift Card         400
Debit Card        359
Debitcard           9
Creditcard          9
Name: count, dtype: int64

In [58]:
df['payment_method'] = df['payment_method'].replace({
      'Creditcard' : 'Credit Card',
      'Debitcard' : 'Debit Card'
})

df['payment_method'].value_counts()

payment_method
Credit Card       423
Cash              418
Mobile Payment    406
Gift Card         400
Debit Card        368
Name: count, dtype: int64

**v. Checking and Cleaning Data  of `return_flag` column :**

In [59]:
df['return_flag'].value_counts()

return_flag
No     1879
Yes     146
Y         6
1         5
0         5
N         4
Name: count, dtype: int64

In [60]:
df['return_flag'] = df['return_flag'].replace({
      'Y' : 'Yes',
      'N' : 'No',
      '1' : 'Yes',
      '0' : 'No'
})

df['return_flag'].value_counts()

return_flag
No     1888
Yes     157
Name: count, dtype: int64

**g. Further duplicate checking :**

**i.  checking all rows :**

In [61]:
print(f"Total dropped duplicates are {df.duplicated().sum()}")

df = df.drop_duplicates().reset_index(drop=True)

Total dropped duplicates are 27

**ii.  Checking duplicates based on `transation_id` :**

In [62]:
suspicious = df[df.duplicated(subset='transaction_id', keep=False)]
print(f"Remaining suspicious duplicated rows: {len(suspicious)}")

for txn_id, group in suspicious.groupby('transaction_id'):
    mismatched_cols = [col for col in group.columns
                       if group[col].nunique(dropna=False) > 1]
    if mismatched_cols:  
        print(f"\ntransaction_id : {txn_id}")
        print(f"Mismatched cols: {mismatched_cols}")
        print(group[['transaction_id'] + mismatched_cols].to_string(index=False))
        print('-' * 60)
    else:
        print(f"\ntransaction_id : {txn_id} → Exact duplicate, need to be dropped")

Remaining suspicious duplicated rows: 36

transaction_id : Txn-00352
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-00352         2
     Txn-00352         1
------------------------------------------------------------

transaction_id : Txn-00396
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-00396         3
     Txn-00396         2
------------------------------------------------------------

transaction_id : Txn-00474
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-00474         3
     Txn-00474         4
------------------------------------------------------------

transaction_id : Txn-00535
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-00535         5
     Txn-00535         4
------------------------------------------------------------

transaction_id : Txn-00854
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-00854         5
     Txn-00854         4
------------------------------------------------------------

transaction_id : Txn-01311
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01311         1
     Txn-01311         2
------------------------------------------------------------

transaction_id : Txn-01346
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01346         2
     Txn-01346         1
------------------------------------------------------------

transaction_id : Txn-01362
Mismatched cols: ['product_name', 'quantity']
transaction_id product_name  quantity
     Txn-01362          NaN         2
     Txn-01362       Laptop         3
------------------------------------------------------------

transaction_id : Txn-01368
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01368         3
     Txn-01368         4
------------------------------------------------------------

transaction_id : Txn-01447
Mismatched cols: ['quantity', 'total_sale']
transaction_id  quantity  total_sale
     Txn-01447         2       54.36
     Txn-01447         3       88.72
------------------------------------------------------------

transaction_id : Txn-01522
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01522         3
     Txn-01522         2
------------------------------------------------------------

transaction_id : Txn-01542
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01542         2
     Txn-01542         1
------------------------------------------------------------

transaction_id : Txn-01617
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01617         2
     Txn-01617         3
------------------------------------------------------------

transaction_id : Txn-01693
Mismatched cols: ['price_per_unit']
transaction_id  price_per_unit
     Txn-01693         -109.11
     Txn-01693          109.11
------------------------------------------------------------

transaction_id : Txn-01742
Mismatched cols: ['membership_tier']
transaction_id membership_tier
     Txn-01742          Bronze
     Txn-01742             NaN
------------------------------------------------------------

transaction_id : Txn-01775
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01775         3
     Txn-01775         2
------------------------------------------------------------

transaction_id : Txn-01826
Mismatched cols: ['quantity']
transaction_id  quantity
     Txn-01826         2
     Txn-01826         1
------------------------------------------------------------

transaction_id : Txn-01983
Mismatched cols: ['city']
transaction_id       city
     Txn-01983        NaN
     Txn-01983 Mymensingh
------------------------------------------------------------

**iii. Resolving `Quantity` and `product_name` Mismatches in Duplicate `transaction_id` Records Using Reverse Calculation :**

In [63]:
df['product_name'] = df.groupby('transaction_id')['product_name'].transform(lambda x: x.ffill().bfill())

mask = df.duplicated(subset='transaction_id', keep=False)
suspicious = df[mask].sort_values('transaction_id')

only_qty_diff = suspicious.groupby('transaction_id').filter(
    lambda g: [c for c in g.columns if g[c].nunique(dropna=False) > 1] == ['quantity']
)

print(len(only_qty_diff))

only_qty_diff = only_qty_diff.copy()

only_qty_diff['actual_qty'] = ((only_qty_diff['total_sale'] + only_qty_diff['discount_amount']) / only_qty_diff['price_per_unit']).round(0).astype(int)

print(only_qty_diff[['transaction_id', 'quantity', 'actual_qty', 'price_per_unit', 'discount_amount', 'total_sale']].to_string(index=False))

28
transaction_id  quantity  actual_qty  price_per_unit  discount_amount  total_sale
     Txn-00352         2           1           36.45             5.47       30.98
     Txn-00352         1           1           36.45             5.47       30.98
     Txn-00396         2           2            7.50             0.75       14.25
     Txn-00396         3           2            7.50             0.75       14.25
     Txn-00474         3           3           63.33            38.00      151.99
     Txn-00474         4           3           63.33            38.00      151.99
     Txn-00535         5           4           69.28            69.28      207.84
     Txn-00535         4           4           69.28            69.28      207.84
     Txn-00854         5           4           89.25             0.00      357.00
     Txn-00854         4           4           89.25             0.00      357.00
     Txn-01311         2           1           47.89             0.00       47.89
     Txn-01311         1           1           47.89             0.00       47.89
     Txn-01346         2           1           36.32             0.00       36.32
     Txn-01346         1           1           36.32             0.00       36.32
     Txn-01362         3           2          946.38           283.91     1608.85
     Txn-01362         2           2          946.38           283.91     1608.85
     Txn-01368         4           3          224.68             0.00      674.04
     Txn-01368         3           3          224.68             0.00      674.04
     Txn-01522         3           2           15.18             1.52       28.84
     Txn-01522         2           2           15.18             1.52       28.84
     Txn-01542         2           1           50.04             2.50       47.54
     Txn-01542         1           1           50.04             2.50       47.54
     Txn-01617         3           2          631.92           252.77     1011.07
     Txn-01617         2           2          631.92           252.77     1011.07
     Txn-01775         2           2          104.68            52.34      157.02
     Txn-01775         3           2          104.68            52.34      157.02
     Txn-01826         1           1           41.23            10.31       30.92
     Txn-01826         2           1           41.23            10.31       30.92

**iv. Replace `quantity` by  `actual_qty` and dropped Duplicate :**

In [64]:
df.loc[only_qty_diff.index, 'quantity'] = only_qty_diff['actual_qty']

print(f"Total dropped duplicates are  {df.duplicated().sum()}")

df = df.drop_duplicates().reset_index(drop=True)

Total dropped duplicates are  14

**v.  Dropping Negative `price_per_unit` in Duplicate `transaction_id` Records:**

In [65]:
neg_price_idx = df[(df['transaction_id'] == 'Txn-01693') & (df['price_per_unit'] < 0)].index

df = df.drop(index=neg_price_idx).reset_index(drop=True)

print(f"Dropped {len(neg_price_idx)} row(s) with negative price_per_unit")
print(df[df['transaction_id'] == 'Txn-01693'][['transaction_id', 'price_per_unit']])

Dropped 1 row(s) with negative price_per_unit
    transaction_id  price_per_unit
242      Txn-01693          109.11

**vi. Dropping `Null` rows in Duplicate `transaction_id` Records:**

In [66]:
for txn_id in ['Txn-01742', 'Txn-01983']:
    group = df[df['transaction_id'] == txn_id]
    
    drop_idx = group.isnull().sum(axis=1).idxmax()
    df = df.drop(index=drop_idx)

df = df.reset_index(drop=True)
print(f"Remaining rows: {len(df)}")
print(f"Remaining duplicate transaction_ids: {df.duplicated(subset='transaction_id').sum()}")

Remaining rows: 2001
Remaining duplicate transaction_ids: 1

Note: Rows for transaction_id Txn-01447 were not dropped. Mismatched quantity and total_sale values suggest these are distinct transactional line items within the same order.

**h. Checking NULL values:**

**i. Checking NULL values:**

In [67]:
df.isnull().sum()

transaction_id         0
sale_date              5
sale_time              0
customer_id            0
gender                40
age                   34
age_group              0
city                  40
store_branch          16
membership_tier       56
sales_channel          0
category               0
product_name          37
quantity               0
price_per_unit         0
cogs                   0
discount_event       891
discount_pct           0
discount_amount        0
total_sale             0
profit                 0
profit_margin_pct      0
payment_method        30
customer_rating       50
return_flag            0
dtype: int64

**ii. Handling missing values:**

**Step-1:** Drop Critical Missing Data by Removing Rows:

In [68]:
df.dropna(subset=['product_name'], inplace = True)
df.reset_index(drop=True, inplace=True)

**Step-2:** Handling missing values of Numerical Data:

**i.** Checking negative numeric values:

In [69]:
numeric_df = df.select_dtypes(include=['number'])
print((numeric_df < 0).sum())

age                  4
quantity             6
price_per_unit       9
cogs                 0
discount_pct         0
discount_amount      0
total_sale           0
profit               0
profit_margin_pct    0
customer_rating      1
dtype: int64

**ii** Convert all negative value and NaN to zero:

In [70]:
cols = ['age', 'quantity', 'price_per_unit', 'customer_rating']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].mask((df[col] < 0) | (df[col].isna()), 0)
    
print(df[cols].eq(0).sum())

age                39
quantity            8
price_per_unit      9
customer_rating    53
dtype: int64

**iii.**  Handling Missing `age` column by using value of `age_group` column :

**Step-1:** Check age within age_group boundaries :

In [71]:
def get_bounds_from_age_group(age_group):
    if pd.isna(age_group):
        return None
    age_group = str(age_group).strip()
    if age_group == '60+':
        return (61, 100)
    elif age_group == 'Under 18':
        return (1, 17)
    elif '-' in age_group:
        parts = age_group.split('-')
        return (int(parts[0]), int(parts[1]))
    return None

def is_out_of_bounds(row):
    if pd.isna(row['age']) or row['age'] == 0: 
        return False
    bounds = get_bounds_from_age_group(row['age_group'])
    if bounds is None:
        return False
    return not (bounds[0] <= row['age'] <= bounds[1])

df['age_invalid'] = df.apply(is_out_of_bounds, axis=1)

invalid_rows = df[df['age_invalid']]
print(f"Total out of boundary age rows: {len(invalid_rows)}")
print(invalid_rows[['transaction_id', 'age', 'age_group']].to_string(index=False))

Total out of boundary age rows: 7
transaction_id   age age_group
     Txn-00447 150.0     36-45
     Txn-01716 150.0     36-45
     Txn-00908 200.0     18-25
     Txn-00686 200.0     36-45
     Txn-01978 999.0     36-45
     Txn-00610 200.0     26-35
     Txn-01329 150.0     46-60

**Step-2:** Covert false age into Zero:

In [72]:
df.loc[df['age_invalid'], 'age'] = 0
df.drop(columns=['age_invalid'], inplace=True)

****Step-3:** Checking age column which providing zero velues:

In [73]:
zero_age_rows = df[df['age'] == 0][['transaction_id', 'product_name', 'age', 'age_group']]

print(len(zero_age_rows))
print(zero_age_rows)

46
     transaction_id    product_name  age age_group
42        Txn-00170           Honey  0.0     46-60
219       Txn-00743    Water Bottle  0.0       60+
253       Txn-00871      Pillow Set  0.0     18-25
305       Txn-01912            Lamp  0.0     18-25
357       Txn-00829            Suit  0.0     36-45
376       Txn-00166          Tablet  0.0     26-35
403       Txn-00016            Lamp  0.0     46-60
409       Txn-01951            Doll  0.0     18-25
462       Txn-00088  Desk Organizer  0.0     36-45
512       Txn-01844         Mascara  0.0     46-60
551       Txn-01143     Moisturizer  0.0     18-25
573       Txn-01063       Olive Oil  0.0     46-60
586       Txn-00447           Honey  0.0     36-45
665       Txn-01465   Chocolate Box  0.0     46-60
742       Txn-01716         Pen Set  0.0     36-45
746       Txn-00908           Novel  0.0     18-25
782       Txn-01095          Hoodie  0.0     36-45
785       Txn-00733           Honey  0.0     46-60
905       Txn-01162      Smartphone  0.0       60+
916       Txn-01033  Organic Coffee  0.0     46-60
1013      Txn-00686        Yoga Mat  0.0     36-45
1042      Txn-00948   Chocolate Box  0.0       60+
1068      Txn-01978            Suit  0.0     36-45
1241      Txn-00443      Headphones  0.0     18-25
1245      Txn-00513          Laptop  0.0       60+
1331      Txn-01980      Board Game  0.0     46-60
1350      Txn-01388            Doll  0.0       60+
1357      Txn-01587           Jeans  0.0     26-35
1384      Txn-01468          Jacket  0.0     46-60
1457      Txn-01940         Tea Set  0.0     36-45
1472      Txn-00694      Pillow Set  0.0     18-25
1490      Txn-00418            Lamp  0.0     46-60
1508      Txn-00648        Curtains  0.0     46-60
1536      Txn-00610  Organic Coffee  0.0     26-35
1573      Txn-00825     Body Lotion  0.0     26-35
1581      Txn-00180        Nuts Mix  0.0       60+
1589      Txn-01241      Smartwatch  0.0     46-60
1630      Txn-00106         Journal  0.0     36-45
1632      Txn-00265         Gym Bag  0.0     46-60
1695      Txn-00947        Yoga Mat  0.0     46-60
1774      Txn-00961      Board Game  0.0       60+
1789      Txn-01083     Protein Bar  0.0     46-60
1823      Txn-00552          Laptop  0.0     26-35
1829      Txn-01886    Water Bottle  0.0     18-25
1884      Txn-00406     Protein Bar  0.0       60+
1901      Txn-01329        Yoga Mat  0.0     46-60

**Step-4:** Fills missing `age` values using the midpoint of the age_group range. For open-ended groups like `60+`, uses the midpoint between the group's lower bound and the dataset's actual maximum age.

In [74]:
max_age = df['age'].max()
print(f'max value of age column :{max_age}')

def age_group_value(age_group):
    if '+' in age_group:
        lower_bound = int(age_group.replace('+', ''))
        return (lower_bound + max_age) // 2
    
    low, high = map(int, age_group.split('-'))
    return (low + high) // 2

df['age'] = df.apply(
           lambda row: age_group_value(row['age_group']) if row['age'] == 0 else row['age'], axis=1)

df['age'] = df['age'].round().astype(int)

max value of age column :70.0

**Step-5:** Further checking :

In [75]:
print(f"Total null of age column: {df['age'].isnull().sum()}")
print(f"Total zero value of age column: {df['age'].eq(0).sum()}")
df.loc[zero_age_rows.index, ['transaction_id', 'product_name', 'age', 'age_group']].head()

Total null of age column: 0
Total zero value of age column: 0

    transaction_id  product_name  age age_group
42       Txn-00170         Honey   53     46-60
219      Txn-00743  Water Bottle   65       60+
253      Txn-00871    Pillow Set   21     18-25
305      Txn-01912          Lamp   21     18-25
357      Txn-00829          Suit   40     36-45

**iv. Handling missing values of `quantity` and `price_per_unit` :**

**Step-1:** Checking missing values of `quantity` and `price_per_unit` :

In [76]:
cols = ['quantity', 'price_per_unit']

zero_rows = df[df[cols].eq(0).any(axis=1)]

print(f"Total zero rows: {len(zero_rows)}")
print(zero_rows[['product_name', 'quantity', 'price_per_unit', 'total_sale', 'cogs', 'profit']])

Total zero rows: 17
        product_name  quantity  price_per_unit  total_sale   cogs  profit
84           Gym Bag         1            0.00       99.16  66.94   32.22
90      Art Supplies         0           18.75       16.87   8.41    8.46
214           Puzzle         0           67.92      203.76  28.23  119.07
295          Pen Set         0           47.29      236.45  14.58  163.55
366             Doll         0           38.19      108.84  15.57   62.13
417        Dumbbells         0          183.29      183.29  77.76  105.53
546       Pillow Set         4            0.00      292.62  50.38   91.10
552         Textbook         3            0.00      171.79  31.55   77.14
569       Candle Set         0           54.88       54.88  25.30   29.58
622            Novel         0           42.01       42.01  17.36   24.65
671            Serum         1            0.00       68.06  24.36   43.70
870             Lamp         1            0.00      117.60  68.79   48.81
1142       Jump Rope         1            0.00      190.80  76.39  114.41
1193      Spice Pack         4            0.00      102.32  16.61   35.88
1264  Desk Organizer         0            6.62        5.63   2.76    2.87
1345         Shampoo         1            0.00       52.90  22.97   29.93
1371        Notebook         1            0.00       23.48  12.47   11.01

**Step-2:** Fillup `quantity` column by using `total_sale` and `price_per_unit` columns :

In [77]:
df['quantity'] = df.apply(
       lambda row: round(row['total_sale'] / row['price_per_unit'])
                   if row['quantity'] == 0 and row['price_per_unit'] != 0
                   else row['quantity'], axis=1
)

**Step-3: Fillup `price_per_unit` column by using `total_sale` and `quantity` columns :**

In [78]:
df['price_per_unit'] = df.apply(
       lambda row: round(row['total_sale'] / row['quantity'], 2)
            if row['price_per_unit'] == 0 and row['quantity'] != 0
            else row['price_per_unit'], axis=1
)

**step-4: Further checking:**

In [79]:
print(f"Total zero rows: {len(zero_rows)}")
print(f"Remaning zero value: \n {df[['quantity', 'price_per_unit']].eq(0).sum()}")
df.loc[zero_rows.index, ['product_name', 'quantity', 'price_per_unit', 'total_sale', 'cogs', 'profit']]

Total zero rows: 17
Remaning zero value:
 quantity          0
price_per_unit    0
dtype: int64

        product_name  quantity  price_per_unit  total_sale   cogs  profit
84           Gym Bag         1           99.16       99.16  66.94   32.22
90      Art Supplies         1           18.75       16.87   8.41    8.46
214           Puzzle         3           67.92      203.76  28.23  119.07
295          Pen Set         5           47.29      236.45  14.58  163.55
366             Doll         3           38.19      108.84  15.57   62.13
417        Dumbbells         1          183.29      183.29  77.76  105.53
546       Pillow Set         4           73.16      292.62  50.38   91.10
552         Textbook         3           57.26      171.79  31.55   77.14
569       Candle Set         1           54.88       54.88  25.30   29.58
622            Novel         1           42.01       42.01  17.36   24.65
671            Serum         1           68.06       68.06  24.36   43.70
870             Lamp         1          117.60      117.60  68.79   48.81
1142       Jump Rope         1          190.80      190.80  76.39  114.41
1193      Spice Pack         4           25.58      102.32  16.61   35.88
1264  Desk Organizer         1            6.62        5.63   2.76    2.87
1345         Shampoo         1           52.90       52.90  22.97   29.93
1371        Notebook         1           23.48       23.48  12.47   11.01

**v. Fixing error values of customer_rating:**

In [82]:
df[df['customer_rating'] > 5][['transaction_id', 'customer_rating']]

     transaction_id  customer_rating
150       Txn-00655              6.5
171       Txn-01216             10.0
300       Txn-00034              9.9
304       Txn-00629             10.0
344       Txn-00894              9.9
641       Txn-00043              9.9
659       Txn-00140              9.9
1256      Txn-01956              6.5
1589      Txn-01241              6.5
1676      Txn-00705              9.9
1753      Txn-00263             10.0

In [83]:
df.loc[df['customer_rating'] > 5, 'customer_rating'] = 0

**vi. Handling missing values of Categorical Data:**

In [84]:
cols_to_unknown = ['gender', 'city', 'store_branch', 'membership_tier', 'discount_event', 'payment_method']

df[cols_to_unknown] = df[cols_to_unknown].fillna('None')

**i. Cross check of Calculated Columns:**

**Step-1:** Cross-check error calculation:

In [85]:
TOLERANCE = 0.01

# --- Recalculate expected values ---
df['expected_discount_amount'] = (df['price_per_unit'] * df['quantity'] * df['discount_pct'] / 100).round(2)
df['expected_total_sale']      = ((df['price_per_unit'] * df['quantity']) - df['expected_discount_amount']).round(2)
df['expected_profit']          = (df['expected_total_sale'] - (df['cogs'] * df['quantity'])).round(2)
df['expected_profit_margin']   = ((df['expected_profit'] / df['expected_total_sale']) * 100).round(2)

# --- Flag mismatched rows ---
df['flag_discount_amount']  = ~np.isclose(df['discount_amount'],  df['expected_discount_amount'], atol=TOLERANCE)
df['flag_total_sale']       = ~np.isclose(df['total_sale'],       df['expected_total_sale'],      atol=TOLERANCE)
df['flag_profit']           = ~np.isclose(df['profit'],           df['expected_profit'],           atol=TOLERANCE)
df['flag_profit_margin']    = ~np.isclose(df['profit_margin_pct'],df['expected_profit_margin'],    atol=TOLERANCE)

# --- Any row that has at least one mismatch ---
any_mismatch = df['flag_discount_amount'] | df['flag_total_sale'] | df['flag_profit'] | df['flag_profit_margin']

# --- Print mismatch summary ---
print("=== Mismatch Count ===")
print(f"discount_amount   : {df['flag_discount_amount'].sum()} rows")
print(f"total_sale        : {df['flag_total_sale'].sum()} rows")
print(f"profit            : {df['flag_profit'].sum()} rows")
print(f"profit_margin_pct : {df['flag_profit_margin'].sum()} rows")
print(f"\nTotal rows with at least one mismatch: {any_mismatch.sum()}")

# --- Print mismatched rows: original vs expected side by side ---
print("\n=== Mismatched Rows (Original vs Expected) ===")
mismatch_view = df.loc[any_mismatch, [
    'transaction_id',
    'quantity', 'price_per_unit', 'cogs', 'discount_pct',
    'discount_amount',   'expected_discount_amount',
    'total_sale',        'expected_total_sale',
    'profit',            'expected_profit',
    'profit_margin_pct', 'expected_profit_margin'
]]

=== Mismatch Count ===
discount_amount   : 8 rows
total_sale        : 27 rows
profit            : 8 rows
profit_margin_pct : 17 rows

Total rows with at least one mismatch: 37

=== Mismatched Rows (Original vs Expected) ===

**Step-2:** Replace all mismatched values with recalculated ones:

In [86]:
# ── Replace all mismatched values with recalculated ones ──────────
df.loc[any_mismatch, 'discount_amount']   = df.loc[any_mismatch, 'expected_discount_amount']
df.loc[any_mismatch, 'total_sale']        = df.loc[any_mismatch, 'expected_total_sale']
df.loc[any_mismatch, 'profit']            = df.loc[any_mismatch, 'expected_profit']
df.loc[any_mismatch, 'profit_margin_pct'] = df.loc[any_mismatch, 'expected_profit_margin']

print(f"Replaced {any_mismatch.sum()} mismatched rows with recalculated values")

# ── Drop helper columns ───────────────────────────────────────────
df.drop(columns=[
    'expected_discount_amount', 'expected_total_sale',
    'expected_profit', 'expected_profit_margin',
    'flag_discount_amount', 'flag_total_sale',
    'flag_profit', 'flag_profit_margin'
], inplace=True)

print(f"Remaining rows : {len(df)}")

Replaced 37 mismatched rows with recalculated values
Remaining rows : 1964

**Step-3:** Final checking:

In [88]:
df.isnull().sum()

transaction_id       0
sale_date            5
sale_time            0
customer_id          0
gender               0
age                  0
age_group            0
city                 0
store_branch         0
membership_tier      0
sales_channel        0
category             0
product_name         0
quantity             0
price_per_unit       0
cogs                 0
discount_event       0
discount_pct         0
discount_amount      0
total_sale           0
profit               0
profit_margin_pct    0
payment_method       0
customer_rating      0
return_flag          0
dtype: int64

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1964 entries, 0 to 1963
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     1964 non-null   str
 1   sale_date          1959 non-null   str
 2   sale_time          1964 non-null   str
 3   customer_id        1964 non-null   str
 4   gender             1964 non-null   str
 5   age                1964 non-null   int64
 6   age_group          1964 non-null   str
 7   city               1964 non-null   str
 8   store_branch       1964 non-null   str
 9   membership_tier    1964 non-null   str
 10  sales_channel      1964 non-null   str
 11  category           1964 non-null   str
 12  product_name       1964 non-null   str
 13  quantity           1964 non-null   int64
 14  price_per_unit     1964 non-null   float64
 15  cogs               1964 non-null   float64
 16  discount_event     1964 non-null   str
 17  discount_pct       1964 non-null   int64
 18  discount_amount    1964 non-null   float64
 19  total_sale         1964 non-null   float64
 20  profit             1964 non-null   float64
 21  profit_margin_pct  1964 non-null   float64
 22  payment_method     1964 non-null   str
 23  customer_rating    1964 non-null   float64
 24  return_flag        1964 non-null   str
dtypes: float64(7), int64(3), str(15)
memory usage: 383.7 KB

In [90]:
df.iloc[:, 20:25].info()

<class 'pandas.DataFrame'>
RangeIndex: 1964 entries, 0 to 1963
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   profit             1964 non-null   float64
 1   profit_margin_pct  1964 non-null   float64
 2   payment_method     1964 non-null   str
 3   customer_rating    1964 non-null   float64
 4   return_flag        1964 non-null   str
dtypes: float64(3), str(2)
memory usage: 76.8 KB

**j. Save the cleaned data to a CSV file:**

In [91]:
df.to_csv('retail_sales_data_cleaned.csv', index='False')